# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Kot Źródłowy
email: korneliak.95@gmial.com
description: > # this means to ignore newlines until "baseurl:"
  To jest blog pisany przez pierwszego kota w IT. Miau!
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://kot-zrodlowy.pl" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: korneliakobiela
github_username:  korneliakobiela
timezone: 'Europe/Warsaw'
disqus:
    shortname: kot-zrodlowy
# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
categories_names:
    'linux': "Linux"
    'dajsiepoznac2017': "Daj się poznać 2017"
    'javascript': "JavaScript"
    'offtop': "Offtop"
    'programowanie': "Programowanie"
    'goscinne': "Wpisy gościnne"
feed:
    path:"/feeds/feed.xml"
